# src/aircontrol/config/gesture_map.yaml

profile: default

bindings:

  - gesture: gesture.pinch
    state: any
    action: mouse.click

  - gesture: gesture.middle_pinch
    state: any
    action: mouse.right_click

  - gesture: gesture.ring_pinch.start
    action: drag.start

  - gesture: gesture.ring_pinch.move
    action: drag.move

  - gesture: gesture.ring_pinch.end
    action: drag.end

  - gesture: gesture.index_middle_pinch
    state: any
    action: cursor.toggle_mode

  - gesture: gesture.fist
    state: any
    action: media.mute_toggle

  - gesture: gesture.volume_up_hold
    state: any
    action: media.volume_up

  - gesture: gesture.volume_down_hold
    state: any
    action: media.volume_down

  - gesture: gesture.vulcan_salute
    state: any
    action: app.quit

  - gesture: gesture.open_palm_hold
    state: any
    action: media.play_pause

  - gesture: gesture.horizontal_yo
    state: any
    action: camera.screenshot

  # - gesture: gesture.call_sign
  #   state: any
  #   action: call.start
  #   params:
  #     number: "+919845103863"
  #     mode: audio

  - gesture: gesture.two_finger_hold
    state: any
    action: scroll.continuous

  - gesture: gesture.flag_wave_right
    state: any
    action: window.left

  - gesture: gesture.flag_wave_left
    state: any
    action: window.right